
# <font color='purple'>**@panData**</font>
# <font color='purple'>**Development and Deployment of Machine Learning Models**</font>
### <font color='purple'>**Deployment of a Machine Learning Model on AWS Cloud for School Managemen**t</font>


## **Python Packages Used in the Project**


In [1]:
!pip install -q -U watermark

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.5 MB/s eta 0:00:00


In [3]:
# Imports
import sklearn
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

In [4]:
%reload_ext watermark
%watermark -a "@panData"

Author: @panData



## **Loading the Data**


In [5]:
# Loading the dataset
df = pd.read_csv('dataset.csv')

In [6]:
# Type of object
type(df)

pandas.core.frame.DataFrame

In [7]:
# Shape
df.shape

(300, 4)

In [8]:
# Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   english_exam_score       300 non-null    float64
 1   qi_value                 300 non-null    int64  
 2   psychometric_exam_score  300 non-null    int64  
 3   admitted                 300 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 9.5 KB


In [9]:
# Data sample
df.head()

english_exam_score  qi_value  psychometric_exam_score  admitted
0                5.41       115                       54         0
1                7.36       105                       77         1
2                7.76        96                       62         1
3                5.51       112                       51         0
4                7.19        97                       47         1

## **Pre-Processing**



In [11]:
# Separating X and y
X = df.drop(columns=['admitted'])
y = df['admitted']

In [12]:
# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [13]:
# Creating the scaler
scaler = StandardScaler()

In [14]:
# Fitting and transforming only on training data
X_train_scaled = scaler.fit_transform(X_train)

In [15]:
# Transforming the test data
X_test_scaled = scaler.transform(X_test)

## **Version 1 - Logistic Regression**

Logistic Regression is a machine learning algorithm used to predict the probability of a categorical dependent variable. Despite its name suggesting regression, it is more commonly used in binary classification problems, where the goal is to predict one of two possible classes (such as "yes" or "no", "1" or "0", "positive" or "negative"). The algorithm models the probability that a given input belongs to a specific category.

The operation of Logistic Regression is based on the concept of the logistic function, also known as the sigmoid function. This function has an "S"-shaped curve, which can map any real number to a value between 0 and 1, making it suitable for estimating probabilities. The model calculates the probability that the input belongs to a specific class and if this probability is greater than a defined threshold (usually 0.5), the input is classified into that class. The logistic function transforms the linear output (a linear combination of independent variables weighted by coefficients, plus an intercept term) into a probability.

In terms of training, Logistic Regression involves adjusting the coefficients of the independent variables. This is done by maximizing the likelihood function, which seeks to find the coefficients that make the predicted probabilities closest to the observed (real) outcomes. Essentially, the algorithm tries to draw a decision boundary that best separates the classes. To evaluate the model's performance, metrics such as accuracy, confusion matrix, AUC-ROC (Area Under the Receiver Operating Characteristic Curve), and others are used.







https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [16]:
# Create the model
model_v1 = LogisticRegression()

In [17]:
# Train the model
model_v1.fit(X_train_scaled, y_train)

LogisticRegression()

In [23]:
# Get class prediction
y_pred_v1 = model_v1.predict(X_test_scaled)

In [20]:
# Get the prediction probabilities
y_pred_proba_v1 = model_v1.predict_proba(X_test_scaled)[:, 1]
y_pred_proba_v1

array([0.98022782, 0.00853758, 0.99728018, 0.92060719, 0.98892818,
       0.91209264, 0.28416158, 0.98112584, 0.994874  , 0.09503492,
       0.95299449, 0.29556171, 0.98998317, 0.92906866, 0.99198539,
       0.87820868, 0.97886576, 0.29048839, 0.81421244, 0.82474907,
       0.02983432, 0.02217034, 0.95288716, 0.29612132, 0.52262812,
       0.05732346, 0.99835783, 0.73443083, 0.24605156, 0.75985974,
       0.92472025, 0.94307055, 0.87640117, 0.05571551, 0.00289766,
       0.96973285, 0.96381592, 0.21160734, 0.9922066 , 0.04271532,
       0.13577308, 0.94727191, 0.20214398, 0.12629434, 0.17176687,
       0.95695546, 0.93632496, 0.10081499, 0.88607713, 0.99830271,
       0.08631244, 0.08880899, 0.06172264, 0.12501502, 0.00634014,
       0.23687371, 0.18384315, 0.03732839, 0.02151441, 0.99482193])

In [25]:
# Calculate accuracy
acc_v1 = accuracy_score(y_test, y_pred_v1)
print(f"\nAccuracy: {acc_v1}")



Accuracy: 0.9


In [26]:
# Calculate accuracy
acc_v1 = accuracy_score(y_test, y_pred_v1)
print(f"\nAccuracy: {acc_v1}")

# Calculate AUC
auc_v1 = roc_auc_score(y_test, y_pred_proba_v1)
print(f"\nAUC: {auc_v1}")

# Generate the classification report
class_report_v1 = classification_report(y_test, y_pred_v1)
print(f"\nClassification Report:\n", class_report_v1)


Accuracy: 0.9

AUC: 0.98

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.87      0.90        30
           1       0.88      0.93      0.90        30

    accuracy                           0.90        60
   macro avg       0.90      0.90      0.90        60
weighted avg       0.90      0.90      0.90        60



## **Version - RandomForest**

The RandomForest algorithm, part of the ensemble methods family, is one of the most popular and versatile machine learning algorithms used for both classification and regression tasks. Its main characteristic is the construction of a collection of decision trees during training, and the model's output is determined by averaging the predictions of all the trees in the case of regression or by majority voting in the case of classification. The name "RandomForest" comes from the way the algorithm creates a "forest" of random decision trees during training.

Each tree in the random forest is built from a random sample of the training data (with replacement), known as bootstrapping, which gives the model the property of being an "ensemble bagging" method. Additionally, at each split of a tree, a random subset of features is selected for consideration, increasing the diversity among the trees and making the model more robust against overfitting. This randomness helps improve the model's accuracy and reduce variance, providing an effective solution for handling large and complex datasets. Individual trees tend to learn and overfit the training data, but when combined in a random forest, the errors of one tree are offset by the correct predictions of others, resulting in improved overall performance.

RandomForest is widely appreciated for its ease of use, as it requires little hyperparameter tuning and generally produces good results with default settings. It is also less prone to overfitting than a single decision tree. Additionally, it offers good interpretability through feature importance, which measures how much each feature contributes to the model's prediction accuracy. However, despite its many advantages, it can be computationally intensive and less efficient in terms of time and memory, especially with a very large number of trees or a very large dataset.

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [27]:
# Create the model
model_v2 = RandomForestClassifier()

In [28]:
# Train the model
model_v2.fit(X_train_scaled, y_train)

RandomForestClassifier()

In [29]:
# Get class prediction
y_pred_v2 = model_v2.predict(X_test_scaled)
y_pred_v2

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [30]:
# Get the prediction probabilities
y_pred_proba_v2 = model_v2.predict_proba(X_test_scaled)[:, 1]
y_pred_proba_v2

array([0.98, 0.  , 1.  , 0.79, 1.  , 0.95, 0.11, 0.99, 1.  , 0.21, 1.  ,
       0.37, 0.94, 0.55, 1.  , 0.93, 0.98, 0.25, 0.98, 0.84, 0.  , 0.  ,
       0.92, 0.36, 0.91, 0.05, 1.  , 0.25, 0.08, 0.55, 1.  , 0.99, 0.96,
       0.  , 0.03, 0.85, 0.46, 0.1 , 0.98, 0.08, 0.11, 0.52, 0.03, 0.05,
       0.05, 0.99, 0.91, 0.1 , 0.97, 0.94, 0.09, 0.08, 0.05, 0.02, 0.07,
       0.29, 0.07, 0.  , 0.07, 1.  ])

In [31]:
# Calculate accuracy
acc_v2 = accuracy_score(y_test, y_pred_v2)
print(f"\nAccuracy: {acc_v2}")


# Calculate AUC
auc_v2 = roc_auc_score(y_test, y_pred_proba_v2)
print(f"\nAUC: {auc_v2}")

# Generate the classification report
class_report_v2 = classification_report(y_test, y_pred_v2)
print(f"\nClassification Report:\n", class_report_v2)


Accuracy: 0.9

AUC: 0.9544444444444445

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.90      0.90        30
           1       0.90      0.90      0.90        30

    accuracy                           0.90        60
   macro avg       0.90      0.90      0.90        60
weighted avg       0.90      0.90      0.90        60




## **Version 3 - Support Vector Machines (SVM)**

Support Vector Machines (SVM) is a powerful and versatile machine learning algorithm primarily used for classification tasks, but it can also be applied to regression. In its simplest and most commonly used form, SVM is employed for binary classification.

The main objective of SVM is to find a hyperplane in an N-dimensional space (N being the number of features) that distinctly classifies the data points into two categories. This hyperplane is chosen to have the maximum possible distance from the nearest data points of each class, known as support vectors. This approach helps to maximize the margin between the classes, contributing to a more robust model with better generalization capabilities.

One of the main strengths of SVM is its ability to work efficiently in high-dimensional spaces and with clear margins of separation between classes. However, when the data is not linearly separable, SVM uses a technique called the "kernel trick." This technique transforms the data into a higher-dimensional space where linear separation is possible. The most common kernels are polynomial, radial basis function (RBF), and sigmoid. This approach makes SVM particularly effective in complex cases where the relationship between features and classes is not immediately apparent.

Despite its advantages, SVM can be challenging in terms of choosing and tuning the correct parameters, such as the type of kernel and kernel parameters, which have a significant impact on the model's performance. Additionally, SVM tends to be less efficient in terms of memory and computationally more intensive, especially with large datasets. It can also be less effective in situations with a high number of features relative to the number of samples or in cases of highly imbalanced classes. Despite these challenges, its effectiveness in separating complex classes makes it a popular choice for classification problems in various fields.



https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

In [32]:
# Create the model
model_v3 = SVC(verbose=True, probability=True)

In [33]:
# Train the model
model_v3.fit(X_train_scaled, y_train)

[LibSVM]

SVC(probability=True, verbose=True)

In [34]:
# Get class prediction
y_pred_v3 = model_v3.predict(X_test_scaled)
y_pred_v3

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [35]:
# Get the prediction probabilities
y_pred_proba_v3 = model_v3.predict_proba(X_test_scaled)[:, 1]
y_pred_proba_v3

array([0.97728408, 0.07604619, 0.93774326, 0.95304194, 0.95782854,
       0.96091894, 0.19673868, 0.97029948, 0.88726244, 0.0514632 ,
       0.96688509, 0.27548132, 0.95996677, 0.66236106, 0.94811392,
       0.94770765, 0.94258716, 0.20868567, 0.91997495, 0.9143762 ,
       0.04575985, 0.05092739, 0.97004191, 0.2025601 , 0.59756332,
       0.03974776, 0.93245558, 0.27418996, 0.06319074, 0.69235204,
       0.96707324, 0.97314486, 0.95320939, 0.0484219 , 0.09901702,
       0.95724375, 0.83878745, 0.14637158, 0.94918963, 0.03769908,
       0.06160073, 0.80913689, 0.33484029, 0.0502532 , 0.06226441,
       0.96839471, 0.9711821 , 0.06174879, 0.95790118, 0.92547842,
       0.04929873, 0.07158255, 0.02967215, 0.16333431, 0.07980778,
       0.37395616, 0.09056082, 0.03612691, 0.0435714 , 0.94625983])

In [36]:
# Calculate accuracy
acc_v3 = accuracy_score(y_test, y_pred_v3)
print(f"\nAccuracy: {acc_v3}")

# Calculate AUC
auc_v3 = roc_auc_score(y_test, y_pred_proba_v3)
print(f"\nAUC: {auc_v3}")

# Generate the classification report
class_report_v3 = classification_report(y_test, y_pred_v3)
print(f"\nClassification Report:\n", class_report_v3)


Accuracy: 0.9166666666666666

AUC: 0.9633333333333334

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.90      0.92        30
           1       0.90      0.93      0.92        30

    accuracy                           0.92        60
   macro avg       0.92      0.92      0.92        60
weighted avg       0.92      0.92      0.92        60



## **Choosing the Model with the Highest AUC**

Here are some reasons to opt for a model with a higher AUC:

**Comprehensive Performance Measure:**  The AUC-ROC is a measure that considers all possible classification thresholds, providing an overall view of the model's performance at different levels of sensitivity and specificity. A model with a higher AUC generally indicates that it has a better ability to distinguish between positive and negative classes across various thresholds.

**Robustness to Class Imbalance:**  In many real-world problems, the number of observations in one class is much larger than in the other, which can lead to a biased model. The AUC-ROC is less affected by class imbalance than other metrics, such as accuracy, because it evaluates the model's performance across all classification thresholds, not just the standard cutoff decision.

**Balance between Sensitivity and Specificity:**  Choosing a model with the highest AUC implies that the model not only correctly identifies true positives (sensitivity) but also correctly excludes true negatives (specificity). This is crucial in many practical applications, such as medical diagnostics, where both false negatives and false positives can have serious consequences.

**Model Comparison:**  The AUC provides a single metric that can be used to compare the performance of different models on a classification problem. This simplifies the choice between models, as a higher AUC generally indicates a model that better performs the task of correctly classifying observations.

**Independence from Decision Threshold:**  Unlike metrics that depend on a specific cutoff point (such as precision, recall, and F1-score), the AUC considers the model's performance across all possible cutoff points. This means that the AUC reflects the quality of the model in terms of its ability to rank predictions correctly, regardless of how the decision threshold is subsequently chosen.

**Probability Predictions:** The ROC curve and, consequently, the AUC are particularly useful when we are interested in predicting class probabilities rather than binary classifications. A model that produces calibrated and discriminative probabilities between classes will have a higher AUC.

In [37]:
# Save the model to disk
pickle.dump(model_v1, open('final_model.pkl', 'wb'))

In [38]:
# Save the scaler
pickle.dump(scaler, open('scaler_final.pkl', 'wb'))

**Crie sua conta na AWS para acompanhar as aulas do deploy do modelo com aplicação web na nuvem**.

In [39]:
%watermark -a "@panData"

Author: @panData



In [40]:
#%watermark -v -m

In [42]:
#%watermark --iversions

🐼❤️